BlueprintMediaServis/BlueprintMediaServis/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlueprintMediaServis.Controllers
{
    public class CatalogController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BlueprintMediaServis/BlueprintMediaServis/Controllers/MagazineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlueprintMediaServis.Models;
using System.IO;
using System.Web.UI.WebControls;

namespace BlueprintMediaServis.Controllers
{
    public class MagazineController : Controller
    {
        public ActionResult Index()
        {
            BlueprintMediaServisEntities1 BMSentity = new BlueprintMediaServisEntities1();

            return View(Tuple.Create<Magazine, IEnumerable<Magazine>>(new Magazine(), BMSentity.Magazines.ToList()));
        }

        [HttpPost]
        public ActionResult Insert(Magazine magazineEntity, HttpPostedFileBase image, HttpPostedFileBase pdf)
        {
            string imagePath = Path.Combine(Server.MapPath("~/Images"), Path.GetFileName(image.FileName));
            string pdfPath = Path.Combine(Server.MapPath("~/Images"), Path.GetFileName(pdf.FileName));

            using (BlueprintMediaServisEntities1 entities = new BlueprintMediaServisEntities1())
            {
                magazineEntity.imageFile = ConvertByte(imagePath, image);
                magazineEntity.pdfFile = ConvertByte(pdfPath, pdf);
                magazineEntity.updateTime = DateTime.Now;
                magazineEntity.createTime = DateTime.Now;
        
                entities.Magazines.Add(magazineEntity);
                entities.SaveChanges();
            }

           return  Redirect(Request.UrlReferrer.ToString());
        }

        
        public ActionResult DisplayPDF(int id)
        {
            var cont = new BlueprintMediaServisEntities1();
            var query = cont.Magazines.ToList();
            var result = query.Where(m => m.id == id).ToList();
            //var query = from magazine in BMSentity.Magazines where (magazine.id == id) select magazine.pdfFile;
            byte[] byteArray = result.Select(m => m.pdfFile).First();
            MemoryStream pdfStream = new MemoryStream();
            pdfStream.Write(byteArray, 0, byteArray.Length);
            pdfStream.Position = 0;
            return new FileStreamResult(pdfStream, "application/pdf");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }


        private Byte[] ConvertByte(string filePath, HttpPostedFileBase f)
        {                    
            string filename = Path.GetFileName(filePath);
            string ext = Path.GetExtension(filename);
            string contenttype = String.Empty;
            
            //Set the contenttype based on File Extension

            switch (ext)
            {                              
                case ".jpg":
                    contenttype = "image/jpg";
                    break;

                case ".png":
                    contenttype = "image/png";
                    break;

                case ".pdf":
                    contenttype = "application/pdf";
                    break;
            }

            if (contenttype != String.Empty)
            {
                Stream fs = f.InputStream;
                BinaryReader br = new BinaryReader(fs);
                Byte[] bytes = br.ReadBytes((Int32)fs.Length);

                return bytes;
            }

            return null;
        }

      



    }
}

BlueprintMediaServis/BlueprintMediaServis/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlueprintMediaServis.Controllers
{
    public class MenuController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BlueprintMediaServis/BlueprintMediaServis/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlueprintMediaServis.Controllers
{
    public class VideoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BlueprintMediaServis/BlueprintMediaServis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(BlueprintMediaServis.Resource.Language.appName,"Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                
                <ul class="nav nav-tabs">
                <li>@Html.ActionLink("En", "Change", "Language", new { LanguageAbbrevation = "en" }, null)</li>
                <li>@Html.ActionLink("Tr", "Change", "Language", new { LanguageAbbrevation = "tr" }, null)</li>
                <li>@Html.ActionLink("Ru", "Change", "Language", new { LanguageAbbrevation = "ru" }, null)</li>

                </ul>

                <ul class="nav navbar-nav ">
                    <li>@Html.ActionLink(BlueprintMediaServis.Resource.Language.home, "Index", "Home")</li>
                    <li>@Html.ActionLink(BlueprintMediaServis.Resource.Language.magazine, "Index", "Magazine")</li>
                    <li>@Html.ActionLink(BlueprintMediaServis.Resource.Language.catalog, "Index", "Catalog")</li>
                    <li>@Html.ActionLink(BlueprintMediaServis.Resource.Language.video, "Index", "Video")</li>
                    <li>@Html.ActionLink(BlueprintMediaServis.Resource.Language.menu, "Index", "Menu")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Blueprint Digital Solutions</p>
        </footer>
    </div>

  
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>